<img src="https://numpy.org/images/logos/numpy.svg">

The fundamental package for scientific computing with Python

https://numpy.org/

* powerful N-dim array object

* broadcasting functions

* LinAlg, Matrix Manipulation, Fourier Series

In [1]:
!pip install numpy

In [2]:
import numpy as np

### Numpy Arrays

* Vector - 1D array


* Matrix - 2D array

In [3]:
mylist = [1,2,3]

In [5]:
type(mylist)

list

In [6]:
type(np.array(mylist))

numpy.ndarray

In [7]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
type(mymatrix)

list

In [9]:
type(np.array(mymatrix))

numpy.ndarray

In [10]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built In Methods

#### arange -
Returns evenly spaced values in given interval

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#### Zeros and Ones

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Linspace -

Returns evenly spaced numbers over a specified interval

In [50]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

#### Identity Matrix

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random Number Generation

#### rand

Creates an array of given shape and populates it with array of uniform distribution over (0,1)

In [23]:
np.random.rand(2)

array([0.60646952, 0.48400759])

#### randn
Returns sample of standard normal distribution

In [24]:
np.random.randn(4)

array([ 1.16581461, -0.3645305 ,  1.02588802,  0.38129504])

In [26]:
np.random.randn(5,5)

array([[ 0.04504038,  0.26234797,  0.87563777,  0.62370201,  1.85319986],
       [ 0.23401525,  0.82444257,  0.5612748 , -0.94721164, -0.51689866],
       [ 1.01065937,  0.64561756, -1.11634715,  2.03449087,  0.21399304],
       [ 0.09878095,  0.27902561, -0.99533311,  0.98662053,  0.14694491],
       [-0.26181701, -0.46646171, -0.99481831, -0.54899662,  0.85076694]])

#### randint

In [30]:
np.random.randint(1,100,10)

array([89, 80, 79, 28, 62,  2, 50, 94, 67, 42])

### Array attributes and methods

In [32]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10)
ranarr

array([13, 33,  3, 37,  1,  9,  1, 36, 47, 20])

#### Reshape

In [39]:
arr.reshape(5,5)#.shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.shape

(25,)

#### max, min, argmax, argmin

In [40]:
ranarr

array([13, 33,  3, 37,  1,  9,  1, 36, 47, 20])

In [44]:
ranarr.min()

1

In [45]:
ranarr.argmin()

4

In [42]:
ranarr.max()

47

In [43]:
ranarr.argmax()

8

# Great Job !